[server]
enableStaticServing = true
headless = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[ui]
hideTopBar = true

[theme]
base = "light"

[global]
disableWatchdogWarning = true

# 👇 THIS IS THE CRITICAL FLAG
[components]
frontEndOverride = "www"