[server]
enableStaticServing = true
staticDir = "www"
headless = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[ui]
hideTopBar = true

[theme]
base = "dark"

[global]
disableWatchdogWarning = true